# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1465, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_condition = QtWidgets.QFrame(self.centralwidget)
        self.frame_condition.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_condition.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_condition.setObjectName("frame_condition")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_condition)
        self.gridLayout.setObjectName("gridLayout")
        self.cb_server_ip = QtWidgets.QCheckBox(self.frame_condition)
        self.cb_server_ip.setObjectName("cb_server_ip")
        self.gridLayout.addWidget(self.cb_server_ip, 0, 0, 1, 1)
        self.le_server_ip = QtWidgets.QLineEdit(self.frame_condition)
        self.le_server_ip.setEnabled(False)
        self.le_server_ip.setObjectName("le_server_ip")
        self.gridLayout.addWidget(self.le_server_ip, 0, 1, 1, 2)
        self.cb_client_ip = QtWidgets.QCheckBox(self.frame_condition)
        self.cb_client_ip.setObjectName("cb_client_ip")
        self.gridLayout.addWidget(self.cb_client_ip, 0, 3, 1, 1)
        self.le_clien_ip = QtWidgets.QLineEdit(self.frame_condition)
        self.le_clien_ip.setEnabled(False)
        self.le_clien_ip.setObjectName("le_clien_ip")
        self.gridLayout.addWidget(self.le_clien_ip, 0, 4, 1, 1)
        self.cb_event = QtWidgets.QCheckBox(self.frame_condition)
        self.cb_event.setObjectName("cb_event")
        self.gridLayout.addWidget(self.cb_event, 1, 0, 1, 1)
        self.cbb_event = QtWidgets.QComboBox(self.frame_condition)
        self.cbb_event.setEnabled(False)
        self.cbb_event.setObjectName("cbb_event")
        self.cbb_event.addItem("")
        self.cbb_event.addItem("")
        self.gridLayout.addWidget(self.cbb_event, 1, 1, 1, 2)
        self.cb_rule = QtWidgets.QCheckBox(self.frame_condition)
        self.cb_rule.setObjectName("cb_rule")
        self.gridLayout.addWidget(self.cb_rule, 1, 3, 1, 1)
        self.le_rule = QtWidgets.QLineEdit(self.frame_condition)
        self.le_rule.setEnabled(False)
        self.le_rule.setObjectName("le_rule")
        self.gridLayout.addWidget(self.le_rule, 1, 4, 1, 1)
        self.cb_uri = QtWidgets.QCheckBox(self.frame_condition)
        self.cb_uri.setObjectName("cb_uri")
        self.gridLayout.addWidget(self.cb_uri, 2, 0, 1, 1)
        self.le_uri = QtWidgets.QLineEdit(self.frame_condition)
        self.le_uri.setEnabled(False)
        self.le_uri.setObjectName("le_uri")
        self.gridLayout.addWidget(self.le_uri, 2, 1, 1, 2)
        self.cb_datetime = QtWidgets.QCheckBox(self.frame_condition)
        self.cb_datetime.setObjectName("cb_datetime")
        self.gridLayout.addWidget(self.cb_datetime, 3, 0, 1, 1)
        self.dte_start = QtWidgets.QDateTimeEdit(self.frame_condition)
        self.dte_start.setEnabled(False)
        self.dte_start.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.dte_start.setCalendarPopup(True)
        self.dte_start.setObjectName("dte_start")
        self.gridLayout.addWidget(self.dte_start, 3, 1, 1, 1)
        self.dte_end = QtWidgets.QDateTimeEdit(self.frame_condition)
        self.dte_end.setEnabled(False)
        self.dte_end.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.dte_end.setCalendarPopup(True)
        self.dte_end.setObjectName("dte_end")
        self.gridLayout.addWidget(self.dte_end, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(803, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 5, 1, 1)
        self.btn_find = QtWidgets.QPushButton(self.frame_condition)
        self.btn_find.setEnabled(False)
        self.btn_find.setObjectName("btn_find")
        self.gridLayout.addWidget(self.btn_find, 3, 6, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_condition)
        self.widget_tableview = QtWidgets.QWidget(self.centralwidget)
        self.widget_tableview.setObjectName("widget_tableview")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_tableview)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_condition = QtWidgets.QPushButton(self.widget_tableview)
        self.btn_condition.setObjectName("btn_condition")
        self.horizontalLayout_2.addWidget(self.btn_condition)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_page = QtWidgets.QLabel(self.widget_tableview)
        self.label_page.setObjectName("label_page")
        self.horizontalLayout_2.addWidget(self.label_page)
        self.btn_pre = QtWidgets.QPushButton(self.widget_tableview)
        self.btn_pre.setObjectName("btn_pre")
        self.horizontalLayout_2.addWidget(self.btn_pre)
        self.btn_next = QtWidgets.QPushButton(self.widget_tableview)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_2.addWidget(self.btn_next)
        self.spinbox_page = QtWidgets.QSpinBox(self.widget_tableview)
        self.spinbox_page.setMinimum(1)
        self.spinbox_page.setMaximum(9999)
        self.spinbox_page.setObjectName("spinbox_page")
        self.horizontalLayout_2.addWidget(self.spinbox_page)
        self.btn_go = QtWidgets.QPushButton(self.widget_tableview)
        self.btn_go.setObjectName("btn_go")
        self.horizontalLayout_2.addWidget(self.btn_go)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView = QtWidgets.QTableView(self.widget_tableview)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout_2.addWidget(self.widget_tableview)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1465, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.menu.addAction(self.action_open)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cb_server_ip.setText(_translate("MainWindow", "服务器IP"))
        self.cb_client_ip.setText(_translate("MainWindow", "客户端IP"))
        self.cb_event.setText(_translate("MainWindow", "事件类型"))
        self.cbb_event.setToolTip(_translate("MainWindow", "<html><head/><body><p>用到再整</p></body></html>"))
        self.cbb_event.setItemText(0, _translate("MainWindow", "sql注入"))
        self.cbb_event.setItemText(1, _translate("MainWindow", "xss"))
        self.cb_rule.setText(_translate("MainWindow", "匹配规则"))
        self.le_rule.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">!</span>表示排除，</p><p><span style=\" font-weight:600;\">;</span>分割语句</p><p>举例：<span style=\" font-weight:600;\">!xss_script_tag;!sql</span></p></body></html>"))
        self.cb_uri.setText(_translate("MainWindow", "URI"))
        self.le_uri.setToolTip(_translate("MainWindow", "<html><head/><body><p>现在只能完全匹配，后续再说</p></body></html>"))
        self.cb_datetime.setText(_translate("MainWindow", "时间介于"))
        self.btn_find.setText(_translate("MainWindow", "查询"))
        self.btn_condition.setText(_translate("MainWindow", "条件"))
        self.label_page.setText(_translate("MainWindow", "n/n"))
        self.btn_pre.setText(_translate("MainWindow", "前一页"))
        self.btn_next.setText(_translate("MainWindow", "下一页"))
        self.spinbox_page.setSuffix(_translate("MainWindow", " 页"))
        self.spinbox_page.setPrefix(_translate("MainWindow", "第 "))
        self.btn_go.setText(_translate("MainWindow", "跳转"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action_open.setText(_translate("MainWindow", "打开"))
        self.action_open.setToolTip(_translate("MainWindow", "打开日志文件"))
